chatroom/urls.py
from django.urls import path

from chatroom import views

app_name = 'chatroom'


urlpatterns = [
    path('', views.ChatDashboardView.as_view(), name='chat_dashboard'),
    path('<int:pk>/', views.ChatRoomView.as_view(), name='room'),
    path('<int:chatroom>/direct/<int:pk>/', views.DirectChatView.as_view(), name='direct_chat'),
    path('sidebar/', views.ChatRoomSidebarView.as_view(), name='sidebar'),
    path('<int:pk>/chatbox/', views.ChatBoxView.as_view(), name='chatbox'),
    path('<int:pk>/users/', views.ChatUsersView.as_view(), name='users'),
    path(
        'send-room-message/', views.SendRoomMessageView.as_view(),
        name='send_room_message'
    ),
    path(
        'send-direct-message/int:<receiver_id>/', views.SendDirectMessageView.as_view(),
        name='send_direct_message'
    ),
    path('ajax/custom/room/', views.ajax_custom_room, name='ajax_custom_room'),
    path('add-friend/<int:userid>/', views.AddFriendView.as_view(), name='add_friend'),
    path('make-friend/<int:userid>/', views.MakeFriendView.as_view(), name='make_friend'),
    path('make-family/<int:userid>/', views.MakeFamilyMemberView.as_view(), name='make_family'),
    path('make-co-worker/<int:userid>/', views.MakeCoWorkerView.as_view(), name='make_co_worker'),
]

django_boilerplate/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import HomeView


urlpatterns = [
    path('management/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('auth/', include('customauth.urls')),
    path('dashboard/', include('dashboard.urls')),
]

wannachat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from wannachat import views


urlpatterns = [
    path('management/', admin.site.urls),

    path('', views.HomeView.as_view(), name='home'),
    path(
        'change-country/', views.ChangeCountryView.as_view(),
        name='change_country'
    ),
    path('faq/', views.FAQPageView.as_view(), name='faq'),
    path('tos/', views.TOSPageView.as_view(), name='tos'),
    path('chat-rules/', views.ChatRulesPageView.as_view(), name='chat_rules'),
    path(
        'safety-tips/', views.SafetyTipsPageView.as_view(), name='safety_tips'
    ),
    path(
        'privacy-policy/', views.PrivacyPolicyPageView.as_view(),
        name='privacy_policy'
    ),
    path(
        'cookie-policy/', views.CookiePolicyPageView.as_view(),
        name='cookie_policy'
    ),
    path(
        'cookie-settings/', views.CookieSettingsPageView.as_view(),
        name='cookie_settings'
    ),
    path('contact/', views.ContactPageView.as_view(), name='contact'),
    path('find-friend/', views.FindFriendView.as_view(), name='find_friend'),

    path('auth/', include('customauth.urls')),
    path('chatroom/', include('chatroom.urls')),
    path('dashboard/', include('dashboard.urls')),
]

# serve media files in development environment --------------------------------
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

chatroom/models/contact.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

chatroom/models/country.py
from django.db import models
from django.utils.text import slugify


class Country(models.Model):
    name = models.CharField(max_length=220, unique=True)
    slug = models.SlugField(max_length=220, unique=True, blank=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Country, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    @property
    def total_chatrooms(self):
        return self.chatroom.all().count()


class State(models.Model):
    country = models.ForeignKey(
        Country, on_delete=models.CASCADE, related_name='states'
    )
    name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('country', 'name')
        ordering = ('name', )

    def __str__(self):
        return self.name

chatroom/views/add_friend.py
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect

from customauth.models import User
from chatroom.models import DirectmessageUser


class AddFriendView(LoginRequiredMixin, View):

    def get(self, request, userid, *args, **kwargs):
        user = User.objects.get(pk=userid)
        friend = DirectmessageUser.objects.get_or_create(
            me=request.user,
            friends=user
        )
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class MakeFriendView(LoginRequiredMixin, View):

    def get(self, request, userid, *args, **kwargs):
        user = User.objects.get(pk=userid)
        friend = DirectmessageUser.objects.get(
            me=request.user,
            friends=user
        )
        friend.friend_type = 'buddies'
        friend.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class MakeFamilyMemberView(LoginRequiredMixin, View):

    def get(self, request, userid, *args, **kwargs):
        user = User.objects.get(pk=userid)
        friend = DirectmessageUser.objects.get(
            me=request.user,
            friends=user
        )
        friend.friend_type = 'family'
        friend.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class MakeCoWorkerView(LoginRequiredMixin, View):

    def get(self, request, userid, *args, **kwargs):
        user = User.objects.get(pk=userid)
        friend = DirectmessageUser.objects.get(
            me=request.user,
            friends=user
        )
        friend.friend_type = 'co-workers'
        friend.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

chatroom/views/ajax.py
from django.shortcuts import HttpResponse
from customauth.models import User
from chatroom.models.category import DirectmessageUser


def ajax_custom_room(request):
    data = request.GET.get('id')
    data = data.split(' ')
    user = User.objects.get(pk=data[0])
    try:
        custom = DirectmessageUser.objects.get(
            friends=user, me=request.user
        )
    except Exception as e:
        custom = DirectmessageUser.objects.create(
            friends=user, friend_type='buddies', me=request.user
        )
    return HttpResponse(user.pk)

chatroom/views/chat_dashboard.py
from django.db.models import Q
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages

from chatroom.models import SubCategory, ChatRoomUser, RoomMessage, DirectMessage, DirectmessageUser
from customauth.models import User


class ChatDashboardView(LoginRequiredMixin, View):
    template_name = "chatroom/dash.html"
    model = SubCategory
    login_url = "/auth/login/"

    def get(self, request, *args, **kwargs):
        chatrooms = ChatRoomUser.objects.filter(user=request.user)
        direct_messages = DirectmessageUser.objects.filter(me=request.user)
        context = {
            'user': request.user,
            'direct_messages': direct_messages,
            'chatrooms': chatrooms,
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        obj = get_object_or_404(self.model, pk=kwargs.get('pk'))
        message_list = RoomMessage.objects.filter(room=obj)
        photo = request.FILES.get('photo')
        name = request.POST.get('name')
        bio = request.POST.get('bio')
        address = request.POST.get('address')
        user = request.user
        if name:
            user.profile.name = name
        if bio:
            user.profile.bio = bio
        if address:
            user.profile.address = address
        if photo:
            user.profile.avatar = photo
        user.profile.save()
        try:
            ChatRoomUser.objects.get(
                user=request.user,
                room=obj
            )
        except ChatRoomUser.DoesNotExist:
            if obj.current_users < obj.max_user:
                ChatRoomUser.objects.create(
                    user=request.user,
                    room=obj
                )
            else:
                messages.warning(request, "This room is full now.")
                return redirect('home')
        chatrooms = ChatRoomUser.objects.filter(user=request.user)
        context = {
            'user': request.user,
            'obj': obj,
            'chatrooms': chatrooms,
            'messages': message_list,
        }
        return render(request, self.template_name, context)

chatroom/views/chatroom.py
from django.db.models import Q
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages

from chatroom.models import SubCategory, ChatRoomUser, RoomMessage, DirectMessage
from customauth.models import User


class ChatRoomView(LoginRequiredMixin, View):
    template_name = "chatroom/room.html"
    model = SubCategory
    login_url = "/auth/login/"

    def get(self, request, *args, **kwargs):
        obj = get_object_or_404(self.model, pk=kwargs.get('pk'))
        message_list = RoomMessage.objects.filter(room=obj)
        try:
            ChatRoomUser.objects.get(
                user=request.user,
                room=obj
            )
        except ChatRoomUser.DoesNotExist:
            if obj.current_users < obj.max_user:
                ChatRoomUser.objects.create(
                    user=request.user,
                    room=obj
                )
            else:
                messages.warning(request, "This room is full now.")
                return redirect('home')
        chatrooms = ChatRoomUser.objects.filter(user=request.user)
        all_direct_chat = request.user.me.all()
        buddies = all_direct_chat.filter(friend_type='buddies')
        family_members = all_direct_chat.filter(friend_type='family')
        co_workers = all_direct_chat.filter(friend_type='co-workers')
        context = {
            'user': request.user,
            'chatroom': obj,
            'chatrooms': chatrooms,
            'messages': message_list,
            'all_direct_chat': all_direct_chat,
            'buddies': buddies,
            'family_members': family_members,
            'co_workers': co_workers
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        obj = get_object_or_404(self.model, pk=kwargs.get('pk'))
        message_list = RoomMessage.objects.filter(room=obj)
        photo = request.FILES.get('photo')
        name = request.POST.get('name')
        bio = request.POST.get('bio')
        address = request.POST.get('address')
        user = request.user
        if name:
            user.profile.name = name
        if bio:
            user.profile.bio = bio
        if address:
            user.profile.address = address
        if photo:
            user.profile.avatar = photo
        user.profile.save()
        try:
            ChatRoomUser.objects.get(
                user=request.user,
                room=obj
            )
        except ChatRoomUser.DoesNotExist:
            if obj.current_users < obj.max_user:
                ChatRoomUser.objects.create(
                    user=request.user,
                    room=obj
                )
            else:
                messages.warning(request, "This room is full now.")
                return redirect('home')
        chatrooms = ChatRoomUser.objects.filter(user=request.user)
        context = {
            'user': request.user,
            'chatroom': obj,
            'chatrooms': chatrooms,
            'messages': message_list,
        }
        return render(request, self.template_name, context)


class DirectChatView(LoginRequiredMixin, View):
    template_name = "chatroom/direct_room.html"
    model = DirectMessage
    login_url = "/auth/login/"

    def get(self, request, chatroom, pk, *args, **kwargs):
        chatroom = get_object_or_404(SubCategory, pk=chatroom)
        obj = get_object_or_404(User, pk=pk)
        message_list = DirectMessage.objects.filter(
            Q(sender_user=obj, receiver_user=request.user) | Q(sender_user=request.user, receiver_user=obj)
        )
        chatrooms = ChatRoomUser.objects.filter(user=request.user)
        all_direct_chat = request.user.me.all()
        buddies = all_direct_chat.filter(friend_type='buddies')
        family_members = all_direct_chat.filter(friend_type='family')
        co_workers = all_direct_chat.filter(friend_type='co-workers')
        context = {
            'user': request.user,
            'obj': obj,
            'chatroom': chatroom,
            'messages': message_list,
            'chatrooms': chatrooms,
            'all_direct_chat': all_direct_chat,
            'buddies': buddies,
            'family_members': family_members,
            'co_workers': co_workers
        }
        return render(request, self.template_name, context)

    def post(self, request, chatroom, pk, *args, **kwargs):
        chatroom = get_object_or_404(SubCategory, pk=chatroom)
        obj = get_object_or_404(User, pk=pk)
        photo = request.FILES.get('photo')
        name = request.POST.get('name')
        bio = request.POST.get('bio')
        address = request.POST.get('address')
        user = request.user
        print(name, bio, address, user, photo, "*" * 100)
        if name:
            user.profile.name = name
        if bio:
            user.profile.bio = bio
        if address:
            user.profile.address = address
        if photo:
            user.profile.avatar = photo
        user.profile.save()
        message_list = DirectMessage.objects.filter(
            Q(sender_user=obj, receiver_user=request.user) | Q(sender_user=request.user, receiver_user=obj)
        )
        chatrooms = ChatRoomUser.objects.filter(user=request.user)
        all_direct_chat = request.user.me.all()
        buddies = all_direct_chat.filter(friend_type='buddies')
        family_members = all_direct_chat.filter(friend_type='family')
        co_workers = all_direct_chat.filter(friend_type='co-workers')
        context = {
            'user': request.user,
            'obj': obj,
            'chatroom': chatroom,
            'messages': message_list,
            'chatrooms': chatrooms,
            'all_direct_chat': all_direct_chat,
            'buddies': buddies,
            'family_members': family_members,
            'co_workers': co_workers
        }
        return render(request, self.template_name, context)


class ChatRoomSidebarView(LoginRequiredMixin, View):
    template_name = "chatroom/userpanel.html"
    model = SubCategory
    login_url = "/auth/login/"

    def get(self, request, *args, **kwargs):
        obj = None
        context = {
            'obj': obj,
        }
        return render(request, self.template_name, context)


class ChatBoxView(LoginRequiredMixin, View):
    template_name = "chatroom/chatbox.html"
    model = SubCategory
    login_url = "/auth/login/"

    def get(self, request, *args, **kwargs):
        obj = get_object_or_404(self.model, pk=kwargs.get('pk'))
        context = {
            'obj': obj,
        }
        return render(request, self.template_name, context)


class ChatUsersView(LoginRequiredMixin, View):
    template_name = "chatroom/chatusers.html"
    model = SubCategory
    login_url = "/auth/login/"

    def get(self, request, *args, **kwargs):
        obj = get_object_or_404(self.model, pk=kwargs.get('pk'))
        context = {
            'obj': obj,
        }
        return render(request, self.template_name, context)

chatroom/views/message.py
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.contrib import messages

from chatroom.models import SubCategory, ChatRoomUser, RoomMessage, DirectMessage


class SendRoomMessageView(View):

    def get(self, request, *args, **kwargs):
        roomid = request.GET.get('roomid')
        email = request.GET.get('email')
        message = request.GET.get('message')
        room = SubCategory.objects.get(id=roomid)
        message_list = RoomMessage.objects.create(
            room=room,
            user=request.user,
            message=message,
        )
        return HttpResponse('SUCCESS')


class SendDirectMessageView(View):
    
    def get(self, request, *args, **kwargs):
        receiver = request.GET.get('receiver_id')
        message = request.GET.get('message')
        receiver_user = User.objects.get(id=receiver)
        DirectMessage.objects.create(
            sender_user=request.user,
            receiver_user=receiver_user,
            message=message
        )
        return HttpResponse('SUCCESS')

templates/chatroom/chatinfo.html
{% load static %}

<div class="offcanvas offcanvas-end offcanvas-aside" data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="offcanvas-more-group">
    <!-- Offcanvas Header -->
    <div class="offcanvas-header py-4 py-lg-7 border-bottom">
        <a class="icon icon-lg text-muted" href="#" data-bs-dismiss="offcanvas">
            <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="feather feather-chevron-left"
            >
                <polyline points="15 18 9 12 15 6"></polyline>
            </svg>
        </a>

        <div class="visibility-xl-invisible overflow-hidden text-center">
            <h5 class="text-truncate">Bootstrap Community</h5>
            <p class="text-truncate">45 members, 9 online</p>
        </div>

        <!-- Dropdown -->
        <div class="dropdown">
            <a class="icon icon-lg text-muted" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    class="feather feather-more-vertical"
                >
                    <circle cx="12" cy="12" r="1"></circle>
                    <circle cx="12" cy="5" r="1"></circle>
                    <circle cx="12" cy="19" r="1"></circle>
                </svg>
            </a>

            <ul class="dropdown-menu">
                <li>
                    <a href="#" class="dropdown-item d-flex align-items-center">
                        Edit
                        <div class="icon ms-auto">
                            <svg
                                xmlns="http://www.w3.org/2000/svg"
                                width="24"
                                height="24"
                                viewBox="0 0 24 24"
                                fill="none"
                                stroke="currentColor"
                                stroke-width="2"
                                stroke-linecap="round"
                                stroke-linejoin="round"
                                class="feather feather-edit-3"
                            >
                                <path d="M12 20h9"></path>
                                <path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z"></path>
                            </svg>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="#" class="dropdown-item d-flex align-items-center">
                        Mute
                        <div class="icon ms-auto">
                            <svg
                                xmlns="http://www.w3.org/2000/svg"
                                width="24"
                                height="24"
                                viewBox="0 0 24 24"
                                fill="none"
                                stroke="currentColor"
                                stroke-width="2"
                                stroke-linecap="round"
                                stroke-linejoin="round"
                                class="feather feather-bell"
                            >
                                <path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9"></path>
                                <path d="M13.73 21a2 2 0 0 1-3.46 0"></path>
                            </svg>
                        </div>
                    </a>
                </li>
                <li>
                    <hr class="dropdown-divider" />
                </li>
                <li>
                    <a href="#" class="dropdown-item d-flex align-items-center text-danger">
                        Leave
                        <div class="icon ms-auto">
                            <svg
                                xmlns="http://www.w3.org/2000/svg"
                                width="24"
                                height="24"
                                viewBox="0 0 24 24"
                                fill="none"
                                stroke="currentColor"
                                stroke-width="2"
                                stroke-linecap="round"
                                stroke-linejoin="round"
                                class="feather feather-log-out"
                            >
                                <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path>
                                <polyline points="16 17 21 12 16 7"></polyline>
                                <line x1="21" y1="12" x2="9" y2="12"></line>
                            </svg>
                        </div>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <!-- Offcanvas Header -->

    <!-- Offcanvas Body -->
    <div class="offcanvas-body hide-scrollbar">

        <!-- Tabs -->
        <ul class="nav nav-pills nav-justified" role="tablist">
            <li class="nav-item">Members</li>
        </ul>
        <!-- Tabs -->

        <!-- Tabs: Content -->
        <div class="tab-content py-2" role="tablist">
            <!-- Members -->
            <div class="tab-pane fade show active" id="offcanvas-group-tab-members" role="tabpanel">
                <ul class="list-group list-group-flush">
                    {% for member in obj.chatroom.all %}
                        <li class="list-group-item">
                            <div class="row align-items-center gx-5">
                                <!-- Avatar -->
                                <div class="col-auto">
                                    <a href="#" class="avatar">
                                        <span class="avatar-text">O</span>
                                    </a>
                                </div>
                                <!-- Avatar -->

                                <!-- Text -->
                                <div class="col">
                                    <h5><a href="#">{{ member.user.profile.name }}</a></h5>
                                    <p>last seen within a week</p>
                                </div>
                                <!-- Text -->

                                <!-- Dropdown -->
                                <div class="col-auto">
                                    <div class="dropdown">
                                        <a class="icon text-muted" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                            <svg
                                                xmlns="http://www.w3.org/2000/svg"
                                                width="24"
                                                height="24"
                                                viewBox="0 0 24 24"
                                                fill="none"
                                                stroke="currentColor"
                                                stroke-width="2"
                                                stroke-linecap="round"
                                                stroke-linejoin="round"
                                                class="feather feather-more-vertical"
                                            >
                                                <circle cx="12" cy="12" r="1"></circle>
                                                <circle cx="12" cy="5" r="1"></circle>
                                                <circle cx="12" cy="19" r="1"></circle>
                                            </svg>
                                        </a>

                                        <ul class="dropdown-menu">
                                            <li>
                                                <a class="dropdown-item d-flex align-items-center" href="#">
                                                    Promote
                                                    <div class="icon ms-auto">
                                                        <svg
                                                            xmlns="http://www.w3.org/2000/svg"
                                                            width="24"
                                                            height="24"
                                                            viewBox="0 0 24 24"
                                                            fill="none"
                                                            stroke="currentColor"
                                                            stroke-width="2"
                                                            stroke-linecap="round"
                                                            stroke-linejoin="round"
                                                            class="feather feather-trending-up"
                                                        >
                                                            <polyline points="23 6 13.5 15.5 8.5 10.5 1 18"></polyline>
                                                            <polyline points="17 6 23 6 23 12"></polyline>
                                                        </svg>
                                                    </div>
                                                </a>
                                            </li>
                                            <li>
                                                <a class="dropdown-item d-flex align-items-center" href="#">
                                                    Restrict
                                                    <div class="icon ms-auto">
                                                        <svg
                                                            xmlns="http://www.w3.org/2000/svg"
                                                            width="24"
                                                            height="24"
                                                            viewBox="0 0 24 24"
                                                            fill="none"
                                                            stroke="currentColor"
                                                            stroke-width="2"
                                                            stroke-linecap="round"
                                                            stroke-linejoin="round"
                                                            class="feather feather-trending-down"
                                                        >
                                                            <polyline points="23 18 13.5 8.5 8.5 13.5 1 6"></polyline>
                                                            <polyline points="17 18 23 18 23 12"></polyline>
                                                        </svg>
                                                    </div>
                                                </a>
                                            </li>
                                            <li><hr class="dropdown-divider" /></li>
                                            <li>
                                                <a class="dropdown-item d-flex align-items-center text-danger" href="{% url 'chatroom:direct_chat' member.user.pk  %}">
                                                    Direct Chat
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                <!-- Dropdown -->
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <!-- Members -->
        </div>
        <!-- Tabs: Content -->
    </div>
    <!-- Offcanvas Body -->
</div>