chatroom/urls.py
from django.urls import path

from chatroom import views

app_name = 'chatroom'


urlpatterns = [
    path('', views.ChatDashboardView.as_view(), name='chat_dashboard'),
    path('<int:pk>/', views.ChatRoomView.as_view(), name='room'),
    path('<int:chatroom>/direct/<int:pk>/', views.DirectChatView.as_view(), name='direct_chat'),
    path('sidebar/', views.ChatRoomSidebarView.as_view(), name='sidebar'),
    path('<int:pk>/chatbox/', views.ChatBoxView.as_view(), name='chatbox'),
    path('<int:pk>/users/', views.ChatUsersView.as_view(), name='users'),
    path(
        'send-room-message/', views.SendRoomMessageView.as_view(),
        name='send_room_message'
    ),
    path(
        'send-direct-message/int:<receiver_id>/', views.SendDirectMessageView.as_view(),
        name='send_direct_message'
    ),
    path('ajax/custom/room/', views.ajax_custom_room, name='ajax_custom_room'),
    path('add-friend/<int:userid>/', views.AddFriendView.as_view(), name='add_friend'),
    path('make-friend/<int:userid>/', views.MakeFriendView.as_view(), name='make_friend'),
    path('make-family/<int:userid>/', views.MakeFamilyMemberView.as_view(), name='make_family'),
    path('make-co-worker/<int:userid>/', views.MakeCoWorkerView.as_view(), name='make_co_worker'),
]

customauth/urls.py
from django.urls import path

from customauth import views

app_name = 'customauth'


urlpatterns = [
    path('admin-login/', views.AdminLoginView.as_view(), name='admin_login'),
    path('admin-logout/', views.user_logout, name='logout'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('signup/', views.UserRegistrationView.as_view(), name='user_signup'),
    path(
        'active-account/<str:token>/', views.AccountActivationView.as_view(),
        name='account_activation'
    ),
    path('load-state/', views.load_state_view, name='load_state'),
    path('welcome/', views.WelcomePageView.as_view(), name='welcome'),
    path('confirmation/', views.ConfirmPageView.as_view(), name='confirmation'),
]

django_boilerplate/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import HomeView


urlpatterns = [
    path('management/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('auth/', include('customauth.urls')),
    path('dashboard/', include('dashboard.urls')),
]

wannachat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from wannachat import views


urlpatterns = [
    path('management/', admin.site.urls),

    path('', views.HomeView.as_view(), name='home'),
    path(
        'change-country/', views.ChangeCountryView.as_view(),
        name='change_country'
    ),
    path('faq/', views.FAQPageView.as_view(), name='faq'),
    path('tos/', views.TOSPageView.as_view(), name='tos'),
    path('chat-rules/', views.ChatRulesPageView.as_view(), name='chat_rules'),
    path(
        'safety-tips/', views.SafetyTipsPageView.as_view(), name='safety_tips'
    ),
    path(
        'privacy-policy/', views.PrivacyPolicyPageView.as_view(),
        name='privacy_policy'
    ),
    path(
        'cookie-policy/', views.CookiePolicyPageView.as_view(),
        name='cookie_policy'
    ),
    path(
        'cookie-settings/', views.CookieSettingsPageView.as_view(),
        name='cookie_settings'
    ),
    path('contact/', views.ContactPageView.as_view(), name='contact'),
    path('find-friend/', views.FindFriendView.as_view(), name='find_friend'),

    path('auth/', include('customauth.urls')),
    path('chatroom/', include('chatroom.urls')),
    path('dashboard/', include('dashboard.urls')),
]

# serve media files in development environment --------------------------------
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

customauth/models/profile.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.dispatch import receiver
from django.db.models.signals import post_save

from customauth.models import User


def avatar_upload_path(instance, filename):
    return f'avatars/{instance.pk}_{filename}'


class Profile(models.Model):
    GENDER_CHOICES = (
        ('male', 'Male'),
        ('female', 'Female'),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(_('Name'), max_length=255, blank=True, null=True)
    gender = models.CharField(
        _('Gender'), max_length=10, choices=GENDER_CHOICES, default='male'
    )
    country = models.ForeignKey(
        'chatroom.Country', on_delete=models.SET_NULL, null=True
    )
    state = models.ForeignKey(
        'chatroom.State', on_delete=models.SET_NULL, null=True
    )
    avatar = models.ImageField(
        upload_to=avatar_upload_path, null=True, blank=True
    )
    bio = models.TextField(
        _('Bio'), max_length=500, blank=True
    )
    address = models.CharField(
        _('Address'), max_length=255, blank=True, null=True
    )
    birth_date = models.DateField(
        _('Date of Birth'), null=True, blank=True
    )

    def __str__(self):
        return self.user.email


@receiver(post_save, sender=User)
def create_or_update_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.get_or_create(user=instance)
    instance.profile.save()

customauth/models/user.py
import uuid
from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser, BaseUserManager, PermissionsMixin
)
from django.utils.translation import gettext_lazy as _


class Usermanager(BaseUserManager):
    """ User manager for user model """
    def _create_user(self, email, password, **extra_fields):
        """ Create and save a user with given email and password """
        if not email:
            raise ValueError('Email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)  # Encrypt password
        user.save(using=self._db)  # safe for multiple databases
        return user

    def create_user(self, email, password=None, **extra_fields):
        """ Create and save a user with given email and password """
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_staffuser(self, email, password, **extra_fields):
        """ Create and save a staff user with given email and password """
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """ Create and save a superuser with given email and password """
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=255, unique=True)
    email = models.CharField(
        _("Email Address"), max_length=255, unique=True, db_index=True
    )
    is_staff = models.BooleanField(_("Staff Status"), default=False)
    is_active = models.BooleanField(_("Active Status"), default=False)
    accepted_terms = models.BooleanField(_("accepted terms"), default=False)
    read_terms = models.BooleanField(_("terms read"), default=False)
    date_joined = models.DateTimeField(_("Date Joined"), auto_now_add=True)
    last_updated = models.DateTimeField(_("Last Updated"), auto_now=True)
    email_token = models.CharField(
        max_length=255, unique=True,
        verbose_name=_("email token"),
        default=uuid.uuid4
    )
    additional_email = models.EmailField(
        _("additional email address"), null=True, blank=True
    )
    verified_email = models.BooleanField(default=False)

    objects = Usermanager()  # Custom user manager

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    def __str__(self):
        return self.email

customauth/forms/login.py
from django import forms


class LoginForm(forms.Form):
    """ Custom login form """
    username_or_email = forms.CharField(
        label="Email",
        max_length=255,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'name': 'username_or_email',
            'placeholder': 'Username or Email',
            'autofocus': True,
        })
    )
    password = forms.CharField(
        label="Password",
        max_length=30,
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'name': 'password',
            'placeholder': 'Password',
        })
    )

customauth/forms/signup.py
from django import forms
from chatroom.models import Country, State


class SignUpForm(forms.Form):
    """ Custom signup form """
    name = forms.CharField(
        label="name",
        max_length=255,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'name': 'name',
            'placeholder': 'Name',
            'autofocus': True,
        })
    )
    username = forms.CharField(
        label="username",
        max_length=255,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'username': 'username',
            'placeholder': 'Username',
            'autofocus': True,
        })
    )
    country = forms.ModelChoiceField(
        label='Country',
        queryset=Country.objects.all(),
        widget=forms.Select(attrs={
            'class': 'form-control',
        })
    )
    state = forms.ModelChoiceField(
        label='State',
        queryset=State.objects.all(),
        widget=forms.Select(attrs={
            'class': 'form-control',
        })
    )
    email = forms.CharField(
        label="Email",
        max_length=255,
        widget=forms.EmailInput(attrs={
            'class': 'form-control',
            'name': 'email',
            'placeholder': 'Email',
            'autofocus': True,
        })
    )
    password = forms.CharField(
        label="Password",
        max_length=30,
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'name': 'password',
            'placeholder': 'Password',
        })
    )
    confirm_password = forms.CharField(
        label="Confirm Password",
        max_length=30,
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'name': 'confirm_password',
            'placeholder': 'Confirm Password',
        })
    )

customauth/views/account_activation.py
import logging
from django.views.generic import View
from django.shortcuts import redirect, get_object_or_404

from customauth.models import User

logger = logging.getLogger(__name__)


class AccountActivationView(View):
    """ Custom login view """

    def get(self, request, token, *args, **kwargs):
        user = get_object_or_404(User, email_token=token)
        if user:
            user.is_active = True
            user.verified_email = True
            user.save()
        return redirect('customauth:confirmation')

customauth/views/load_state.py
from django.shortcuts import render

from chatroom.models import Country, State


def load_state_view(request):
    country = request.GET.get('country')
    state_list = State.objects.filter(country__pk=country)
    context = {
        'state_list': state_list,
    }
    return render(request, 'customauth/load_state.html', context)

customauth/views/login.py
import logging
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib import messages

from customauth.forms import LoginForm

logger = logging.getLogger(__name__)


class AdminLoginView(LoginView):
    """ Custom login view """
    template_name = 'customauth/adminlogin.html'
    form_class = LoginForm

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('dashboard:dashboard')
        form = self.form_class
        context = {
            'form': form,
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('dashboard:dashboard')
        form = self.form_class(request.POST)
        if form.is_valid():
            email = form.cleaned_data['username_or_email']
            password = form.cleaned_data['password']
            user = authenticate(email=email, password=password)
            if user:
                login(request, user)
                return redirect('dashboard:dashboard')
            else:
                messages.error(request, 'Invalid email or password')
        else:
            print(form.errors)
            logger.error(f'Invalid form data: {form.errors}')
            messages.error(
                request, 'Invalid email or password. Please enter correctly.'
            )
        context = {
            'form': form,
        }
        return render(request, self.template_name, context)

customauth/views/logout.py
from django.shortcuts import redirect
from django.contrib.auth import logout


def user_logout(request):
    logout(request)
    return redirect('customauth:admin_login')

templates/customauth/load_state.html
<option value="">---------</option>
{% for state in state_list %}
    <option value="{{ state.pk }}">{{ state.name }}</option>
{% endfor %}

templates/customauth/login.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <!-- Head -->
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, maximum-scale=1, shrink-to-fit=no, viewport-fit=cover" />
        <meta name="color-scheme" content="light dark" />

        <title>Login | WannaChat</title>

        <!-- Favicon -->
        <link rel="shortcut icon" href="assets/img/favicon/favicon.ico" type="image/x-icon" />

        <!-- Font -->
        <link rel="preconnect" href="../../../../fonts.gstatic.com/index.html" />
        <link href="../../../../fonts.googleapis.com/css2f74f.css?family=Roboto:wght@400;500;700" rel="stylesheet" />

        <!-- Template CSS -->
        <link class="css-lt" rel="stylesheet" href="{% static 'assets/css/template.bundle.css' %}" media="(prefers-color-scheme: light)" />
        <link class="css-dk" rel="stylesheet" href="{% static 'assets/css/template.dark.bundle.css' %}" media="(prefers-color-scheme: dark)" />

        <!-- Theme mode -->
        <script>
            if (localStorage.getItem("color-scheme")) {
                let scheme = localStorage.getItem("color-scheme");

                const LTCSS = document.querySelectorAll("link[class=css-lt]");
                const DKCSS = document.querySelectorAll("link[class=css-dk]");

                [...LTCSS].forEach((link) => {
                    link.media = scheme === "light" ? "all" : "not all";
                });

                [...DKCSS].forEach((link) => {
                    link.media = scheme === "dark" ? "all" : "not all";
                });
            }
        </script>
    </head>

    <body class="bg-light">
        <div class="container">
            <div class="row align-items-center justify-content-center min-vh-100 gx-0">
                <div class="col-12 col-md-5 col-lg-4">
                    <div class="card card-shadow border-0">
                        <div class="card-body">
                            <form action="" method="post">
                                {% csrf_token %}
                                <div class="row g-6">
                                    <div class="col-12">
                                        <div class="text-center">
                                            <h2 class="fw-bold mb-2">
                                                <a href="{% url 'home' %}">WannaChat</a>
                                            </h2>
                                            <hr>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="text-center">
                                            <h3 class="fw-bold mb-2">Sign In</h3>
                                            <p>Login to your account</p>
                                            {% if messages %}
                                                <div class="messages text-center">
                                                    {% for message in messages %}
                                                        <div{% if message.tags %}
                                                            class="alert alert-sm alert-danger"{% endif %}>
                                                            {{ message }}
                                                        </div>
                                                    {% endfor %}
                                                </div>
                                            {% endif %}
                                        </div>
                                    </div>
    
                                    <div class="col-12">
                                        <div class="form-floating">
                                            {{ form.username_or_email }}
                                            <label for="id_username_or_email">Username or Email</label>
                                        </div>
                                    </div>
    
                                    <div class="col-12">
                                        <div class="form-floating">
                                            {{ form.password }}
                                            <label for="id_password">Password</label>
                                        </div>
                                    </div>
    
                                    <div class="col-12">
                                        <button class="btn btn-block btn-lg text-white w-100" type="submit" style="background-color: #17a2b8;">Sign In</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>

                    <!-- Text -->
                    <div class="text-center mt-8">
                        <p>Don't have an account yet? <a href="{% url 'customauth:user_signup' %}">Sign up</a></p>
                        <p><a href="password-reset.html">Forgot Password?</a></p>
                    </div>
                </div>
            </div>
            <!-- / .row -->
        </div>

        <!-- Scripts -->
        <script src="{% static 'assets/js/vendor.js' %}"></script>
        <script src="{% static 'assets/js/template.js' %}"></script>
    </body>
</html>

templates/customauth/new_login.html
<!DOCTYPE html>
<html lang="en">
   {% load static %}
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Wanna Chat || Login</title>
        <link href="https://fonts.googleapis.com/css2?family=Labrada:wght@200;300&family=Roboto:wght@100&display=swap" rel="stylesheet" />
        <link rel="stylesheet" href="{% static 'home/assets/login.css' %}" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    </head>
    <body>
        <section class="row mt-4">
            <div class="col-md-4 offset-md-4">
                <form action="" method="post" style="box-shadow: 4px 4px 7px 7px lightgray !important; padding: 25px;">
                  {% csrf_token %}
                    <h3 class="title-login" style="text-align: center;"><b>Wanna Chat</b></h3>
                    <hr />
                    <p style="text-align: center;"><b>Login</b></p>
                    {% if messages %}
                        <div class="messages text-center">
                              {% for message in messages %}
                                 <div{% if message.tags %}
                                    class="alert alert-sm alert-danger"{% endif %}>
                                    {{ message }}
                                 </div>
                              {% endfor %}
                        </div>
                     {% endif %}
                    <div class="form-group">
                        <label for="id_username_or_email">username or email</label>
                        {{ form.username_or_email }}
                    </div>
                    <div class="form-group">
                        <label for="id_password">password</label>
                        {{ form.password }}
                    </div>
                    <br />
                    <div class="d-flex justify-content-center">
                        <button class="btn-info login align-center">login</button>
                    </div>
                    <div class="text-center">
                        <br />
                        <a href="#" target="_blank" rel="noopener">forgot password</a>
                        |
                        <a href="{% url 'customauth:user_signup' %}" class="text-center" target="_blank" rel="noopener">sign up</a>
                    </div>
                </form>
            </div>
        </section>
    </body>
</html>

templates/customauth/signup.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <!-- Head -->
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, maximum-scale=1, shrink-to-fit=no, viewport-fit=cover" />
        <meta name="color-scheme" content="light dark" />

        <title>Signup | WannaChat</title>

        <!-- Favicon -->
        <link rel="shortcut icon" href="assets/img/favicon/favicon.ico" type="image/x-icon" />

        <!-- Font -->
        <link rel="preconnect" href="../../../../fonts.gstatic.com/index.html" />
        <link href="../../../../fonts.googleapis.com/css2f74f.css?family=Roboto:wght@400;500;700" rel="stylesheet" />

        <!-- Template CSS -->
        <link class="css-lt" rel="stylesheet" href="{% static 'assets/css/template.bundle.css' %}" media="(prefers-color-scheme: light)" />
        <link class="css-dk" rel="stylesheet" href="{% static 'assets/css/template.dark.bundle.css' %}" media="(prefers-color-scheme: dark)" />

        <!-- Theme mode -->
        <script>
            if (localStorage.getItem("color-scheme")) {
                let scheme = localStorage.getItem("color-scheme");

                const LTCSS = document.querySelectorAll("link[class=css-lt]");
                const DKCSS = document.querySelectorAll("link[class=css-dk]");

                [...LTCSS].forEach((link) => {
                    link.media = scheme === "light" ? "all" : "not all";
                });

                [...DKCSS].forEach((link) => {
                    link.media = scheme === "dark" ? "all" : "not all";
                });
            }
        </script>
    </head>

    <body class="bg-light">
        <div class="container">
            <div class="row align-items-center justify-content-center min-vh-100 gx-0">
                <div class="col-12 col-md-6 col-lg-6">
                    <div class="card card-shadow border-0">
                        <div class="card-body">
                            <form action="" method="post" id="registerForm" data-state-url="{% url 'customauth:load_state' %}">
                                {% csrf_token %}
                                <div class="row g-6">
                                    <div class="col-12">
                                        <div class="text-center">
                                            <h2 class="fw-bold mb-2">
                                                <a href="{% url 'home' %}">WannaChat</a>
                                            </h2>
                                            <hr>
                                        </div>
                                    </div>
    
                                    <div class="col-12">
                                        <div class="text-center">
                                            <h3 class="fw-bold mb-2">Sign Up</h3>
                                            <p>Follow the easy steps</p>
                                            <b class="text-center text-danger">{{ message }}</b>
                                        </div>
                                    </div>
    
                                    <div class="col-12">
                                        <div class="form-floating">
                                            {{ form.name }}
                                            <label for="id_name">Name</label>
                                        </div>
                                    </div>
    
                                    <div class="col-12">
                                        <div class="form-floating">
                                            {{ form.username }}
                                            <label for="id_username">Username</label>
                                        </div>
                                    </div>

                                    <div class="col-12">
                                        <div class="form-floating">
                                            <div class="col-md-12">
                                                <div class="radio" style="display: flex;">
                                                    <div style="width: 50%; border: 1px solid #ced4da; padding: 10px; border-radius: 5px;">
                                                        <label>
                                                            <input type="radio" name="gender" value="male" id="gender-male" />
                                                            <span>Male</span>
                                                            <img src="{% static 'assets/img/man.png' %}" alt="" height="35px">
                                                        </label>
                                                    </div>
                                                    <div style="width: 49%; border: 1px solid #ced4da; padding: 10px; border-radius: 5px; margin-left: 20px;">
                                                        <label>
                                                            <input type="radio" name="gender" value="female" id="gender-female" />
                                                            <span>Female</span>
                                                            <img class="text-right" src="{% static 'assets/img/female.png' %}" alt="" height="35px">
                                                        </label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-6">
                                        <div class="form-floating">
                                            {{ form.country }}
                                            <label for="id_country">Country</label>
                                        </div>
                                    </div>
                                    <div class="col-6">
                                        <div class="form-floating">
                                            {{ form.state }}
                                            <label for="id_state">State</label>
                                        </div>
                                    </div>
    
                                    <div class="col-12">
                                        <div class="form-floating">
                                            {{ form.email }}
                                            <label for="id_email">Email</label>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="form-floating">
                                            {{ form.password }}
                                            <label for="id_password">Password</label>
                                        </div>
                                    </div>
    
                                    <div class="col-12">
                                        <div class="form-floating">
                                            {{ form.confirm_password }}
                                            <label for="id_confirm_password">Confirm Password</label>
                                        </div>
                                    </div>
    
                                    <div class="col-12">
                                        <button class="btn btn-block btn-lg text-white w-100" type="submit" style="background-color: #17a2b8;">Create Account</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>

                    <!-- Text -->
                    <div class="text-center mt-8">
                        <p>Already have an account? <a href="{% url 'customauth:user_login' %}">Sign in</a></p>
                    </div>
                </div>
            </div>
            <!-- / .row -->
        </div>

        <!-- Scripts -->
        <script src="{% static 'assets/js/vendor.js' %}"></script>
        <script src="{% static 'assets/js/template.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script>
            $("#id_country").change(function () {
            var url = $("#registerForm").attr("data-state-url");
            var country = $(this).val();
            $.ajax({
                url: url,
                data: {
                    'country': country
                },
                success: function (data) {
                    $("#id_state").html(data);
                }
            });
        });
        </script>
    </body>
</html>