chatroom/urls.py
from django.urls import path

from chatroom import views

app_name = 'chatroom'


urlpatterns = [
    path('', views.ChatDashboardView.as_view(), name='chat_dashboard'),
    path('<int:pk>/', views.ChatRoomView.as_view(), name='room'),
    path('<int:chatroom>/direct/<int:pk>/', views.DirectChatView.as_view(), name='direct_chat'),
    path('sidebar/', views.ChatRoomSidebarView.as_view(), name='sidebar'),
    path('<int:pk>/chatbox/', views.ChatBoxView.as_view(), name='chatbox'),
    path('<int:pk>/users/', views.ChatUsersView.as_view(), name='users'),
    path(
        'send-room-message/', views.SendRoomMessageView.as_view(),
        name='send_room_message'
    ),
    path(
        'send-direct-message/int:<receiver_id>/', views.SendDirectMessageView.as_view(),
        name='send_direct_message'
    ),
    path('ajax/custom/room/', views.ajax_custom_room, name='ajax_custom_room'),
    path('add-friend/<int:userid>/', views.AddFriendView.as_view(), name='add_friend'),
    path('make-friend/<int:userid>/', views.MakeFriendView.as_view(), name='make_friend'),
    path('make-family/<int:userid>/', views.MakeFamilyMemberView.as_view(), name='make_family'),
    path('make-co-worker/<int:userid>/', views.MakeCoWorkerView.as_view(), name='make_co_worker'),
]

customauth/urls.py
from django.urls import path

from customauth import views

app_name = 'customauth'


urlpatterns = [
    path('admin-login/', views.AdminLoginView.as_view(), name='admin_login'),
    path('admin-logout/', views.user_logout, name='logout'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('signup/', views.UserRegistrationView.as_view(), name='user_signup'),
    path(
        'active-account/<str:token>/', views.AccountActivationView.as_view(),
        name='account_activation'
    ),
    path('load-state/', views.load_state_view, name='load_state'),
    path('welcome/', views.WelcomePageView.as_view(), name='welcome'),
    path('confirmation/', views.ConfirmPageView.as_view(), name='confirmation'),
]

django_boilerplate/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import HomeView


urlpatterns = [
    path('management/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('auth/', include('customauth.urls')),
    path('dashboard/', include('dashboard.urls')),
]

wannachat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from wannachat import views


urlpatterns = [
    path('management/', admin.site.urls),

    path('', views.HomeView.as_view(), name='home'),
    path(
        'change-country/', views.ChangeCountryView.as_view(),
        name='change_country'
    ),
    path('faq/', views.FAQPageView.as_view(), name='faq'),
    path('tos/', views.TOSPageView.as_view(), name='tos'),
    path('chat-rules/', views.ChatRulesPageView.as_view(), name='chat_rules'),
    path(
        'safety-tips/', views.SafetyTipsPageView.as_view(), name='safety_tips'
    ),
    path(
        'privacy-policy/', views.PrivacyPolicyPageView.as_view(),
        name='privacy_policy'
    ),
    path(
        'cookie-policy/', views.CookiePolicyPageView.as_view(),
        name='cookie_policy'
    ),
    path(
        'cookie-settings/', views.CookieSettingsPageView.as_view(),
        name='cookie_settings'
    ),
    path('contact/', views.ContactPageView.as_view(), name='contact'),
    path('find-friend/', views.FindFriendView.as_view(), name='find_friend'),

    path('auth/', include('customauth.urls')),
    path('chatroom/', include('chatroom.urls')),
    path('dashboard/', include('dashboard.urls')),
]

# serve media files in development environment --------------------------------
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

chatroom/views/message.py
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.contrib import messages

from chatroom.models import SubCategory, ChatRoomUser, RoomMessage, DirectMessage


class SendRoomMessageView(View):

    def get(self, request, *args, **kwargs):
        roomid = request.GET.get('roomid')
        email = request.GET.get('email')
        message = request.GET.get('message')
        room = SubCategory.objects.get(id=roomid)
        message_list = RoomMessage.objects.create(
            room=room,
            user=request.user,
            message=message,
        )
        return HttpResponse('SUCCESS')


class SendDirectMessageView(View):
    
    def get(self, request, *args, **kwargs):
        receiver = request.GET.get('receiver_id')
        message = request.GET.get('message')
        receiver_user = User.objects.get(id=receiver)
        DirectMessage.objects.create(
            sender_user=request.user,
            receiver_user=receiver_user,
            message=message
        )
        return HttpResponse('SUCCESS')

templates/home copy.html
<!DOCTYPE html>
<html lang="en">
   {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>WannaChat</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
        <link href="{% static 'home/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" style="background: #86efac;">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#!">WannaChat</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">Home</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">New York</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#!">MNH</a></li>
                                <li><a class="dropdown-item" href="#!">BRK</a></li>
                                <li><a class="dropdown-item" href="#!">QUE</a></li>
                            </ul>
                        </li>
                    </ul>
                    <ul class="navbar-nav ">
                       <li class="nav-item text-right"><a class="nav-link active text-right" aria-current="page" href="">{{ request.user.email }}</a></li>
                    </ul>
                    <div class="d-flex">
                        {% if request.user.is_authenticated %}
                           <a href="{% url 'customauth:user_logout' %}" class="button">Logout</a>
                        {% else %}
                           <a href="{% url 'customauth:user_signup' %}" class="button">Register</a>
                           <a href="{% url 'customauth:user_login' %}" class="button">Login</a>
                        {% endif %}
                        <select class="language">
                            <option selected>EN</option>
                            <option value="1">ESP</option>
                            <option value="2">DE</option>
                            <option value="3">RU</option>
                        </select>
                    </div>
                </div>
            </div>
        </nav>
        <!-- Section-->
        <section class="py-4">
            <div class="container px-4 px-lg-5">
                <div class="row justify-content-center">
                    <!-- section 1 -->
                    <div class="col-md-2 text-center">
                        <div class="card h-100">
                            <div class="card-body" style="background: #f0fdf4;">
                                <ul class="py-3 ps-0">
                                    <li class="leftCard-search">
                                        <form action="" method="get">
                                            <input class="form-control me-2" type="search" name="search" placeholder="&#x1F50D Search" aria-label="Search" />
                                        </form>
                                    </li>
                                </ul>
                                <p>wanna join</p>
                                <p>wanna join</p>
                                <p>wanna join</p>
                                <p>wanna join</p>
                                <p>wanna join</p>
                                <p>wanna join</p>
                            </div>
                        </div>
                    </div>

                    <!-- section 2 -->
                    <div class="col-md-8">
                        <div class="row">
                           {% for category in category_list %}
                            <div class="col-md-4 mb-4 category-section">
                                <div class="category-card">
                                    <div class="card-header category-header">
                                        <b>{{ category.name }}</b>
                                    </div>
                                    <div class="card-body category-body">
                                        <div class="row">
                                            <div class="col-md-12">
                                                {% for subcategory in category.sub_categories.all %}
                                                <li class="sub-category">
                                                    {% if category.category_type == 'chatroom' %}
                                                        {% url 'chatroom:sidebar' as userpanel %}
                                                        {% url 'chatroom:chatbox' subcategory.pk as chatbox %}
                                                        {% url 'chatroom:users' subcategory.pk as users %}
                                                        <button class="chatroom" onclick="openChatWindow('{{ userpanel }}', '{{ chatbox }}', '{{ users }}')">{{ subcategory.name }}</button>
                                                    {% else %}
                                                        <a href="">{{ subcategory.name }}</a>
                                                    {% endif %}
                                                </li>
                                                {% endfor %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>

                    <!-- section 3 -->
                    <div class="col-md-2 text-center">
                        <div class="card h-100" style="margin-left: -20px;">
                            <div class="card-header" style="background: #dcfce7;">
                                <b>Near by CF</b>
                            </div>
                            <div class="card-body" style="background: #f0fdf4;">
                                <p>wanna join</p>
                                <p>wanna join</p>
                                <p>wanna join</p>
                                <p>wanna join</p>
                                <p>wanna join</p>
                                <p>wanna join</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="py-5">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'home/js/scripts.js' %}"></script>
        <script>
            function openChatWindow(userpanel, chatbox, users) {  
                window.open(userpanel, "My Panel", "toolbar=no,status=no,menubar=no,location=left,scrollbars=no,resizable=no,height=600,width=357");
                window.open(chatbox, "Chat Box", "height=600,width=657,screenX=500");
                window.open(users,"Users","height=600,width=357,screenX=1200");
            } 
        </script>
    </body>
</html>

templates/home_old.html
<!DOCTYPE html>
<html lang="en">
   {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="If you are looking for Free Online Chatrooms or to Random Video Chat with strangers look no further! This is an awesome community that allows you to start or join a free online chat room with strangers, private message, and network with like-minded people who share the same hobbies and interests as you. If you make a friend, add them to your buddy list to keep in touch in the future! Our Free Random Video Chat is the perfect Omegle alternative that lets you meet new interesting people in real-time, based on similar interests!" />
        <meta name="author" content="WannaChat.org" />
        <title>Welcome to WannaChat.org!</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
        <link href="{% static 'home/css/styles.css' %}" rel="stylesheet" />
        <style>
            .rows{
                --bs-gutter-x: 1.5rem;
                --bs-gutter-y: 0;
                display: block !important;;
                flex-wrap: wrap;
                margin-top: calc(-1 * var(--bs-gutter-y));
                margin-right: calc(-0.5 * var(--bs-gutter-x));
                margin-left: calc(-0.5 * var(--bs-gutter-x));
            }
            .col-md-6s{
                width: 50%;
                float: left;
                padding: 0 15px;
            }
        </style>
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" style="background: #1dbbd6;">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'home' %}">
                    <img src="{% static 'logo2.jpeg' %}" alt="Logo" height="40px" width="40px">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active button" aria-current="page" href="{% url 'home' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link active button" aria-current="page" href="">About Us</a></li>
                        <li class="nav-item"><a class="nav-link active button" aria-current="page" href="">Contact Us</a></li>
                        <li class="nav-item dropdown">
                            <select class="country" id="country" name="country">
                                {% for country in country_list %}
                                    <option {% if selected_country.name == country.name %}selected{% endif %}>{{ country.name }}</option>
                                {% endfor %}
                            </select>
                        </li>
                    </ul>
                    <ul class="navbar-nav ">
                       <li class="nav-item text-right"><a class="nav-link active text-right" aria-current="page" href="">{{ request.user.email }}</a></li>
                    </ul>
                    <div class="d-flex">
                        {% if request.user.is_authenticated %}
                           <a href="{% url 'customauth:user_logout' %}" class="button">Logout</a>
                        {% else %}
                           <a href="{% url 'customauth:user_signup' %}" class="button">Register</a>
                           <a href="{% url 'customauth:user_login' %}" class="button">Login</a>
                        {% endif %}
                        <select class="language">
                            <option selected>EN</option>
                            <option value="1">ESP</option>
                            <option value="2">DE</option>
                            <option value="3">RU</option>
                        </select>
                    </div>
                </div>
            </div>
        </nav>
        <!-- Section-->
        <section class="py-4">
            <div class="container px-4 px-lg-5">
                <div class="row justify-content-center">
                    <!-- section 1 -->
                    <div class="col-md-4">
                        <div class="card h-100">
                            <div class="card-body" style="background: #1dbbd6;">
                                <ul class="py-3 ps-0">
                                    <li class="leftCard-search">
                                        <form action="" method="get">
                                            <input class="form-control me-2" type="search" name="search" placeholder="&#x1F50D Search" aria-label="Search" />
                                        </form>
                                    </li>
                                </ul>
                                <div class="mt-4">
                                    <h4 class="text-center">Welcome to WannaChat.org!</h4>
                                    <p>If you are looking for Free Online Chatrooms or to Random Video Chat with strangers look no further! This is an awesome community that allows you to start or join a free online chat room with strangers, private message, and network with like-minded people who share the same hobbies and interests as you. If you make a friend, add them to your buddy list to keep in touch in the future!</p>
                                    <p>Our Free Random Video Chat is the perfect Omegle alternative that lets you meet new interesting people in real-time, based on similar interests!</p>
                                </div>
                                <div class="mt-4">
                                    <h5>Chatroom Rules:</h5>
                                    <li>* You are 18+ years old</li>
                                    <li>* Do not use illegal drugs on cam</li>
                                    <li>* No degrading others on religion, race, or sexual orientation in the chat</li>
                                    <li>* No obscene actions</li>
                                    <li>* No pishing/scamming</li>
                                    <li>* Do not ask or provide others with personal information</li>
                                </div>
                                <div class="mt-4">
                                    <ul style="padding: 0px;">
                                        <li><a href="{% url 'faq' %}">F.A.Q.</a></li>
                                        <li><a href="{% url 'tos' %}">T.O.S</a></li>
                                        <li><a href="{% url 'chat_rules' %}">Chat Rules</a></li>
                                        <li><a href="{% url 'safety_tips' %}">Safety Tips</a></li>
                                        <li><a href="{% url 'privacy_policy' %}">Privacy Policy</a></li>
                                        <li><a href="{% url 'cookie_policy' %}">Cookie Policy</a></li>
                                        <li><a href="{% url 'cookie_settings' %}">Cookie Settings</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- section 2 -->
                    <div class="col-md-8">
                        <div class="rows">
                            {% for category in category_list %}
                                <div class="col-md-6s">
                                    <div class="category-heading py-2 text-center">
                                        <h4 class="fw-bold">{{ category.name }}</h4>
                                    </div>
                                    <div class="row">
                                        {% for subcategory in category.sub_categories.all %}
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-6">
                                            <ul class="ps-0">
                                                <li class="cat-list">
                                                    {% if category.category_type == 'chatroom' %}
                                                        {% url 'chatroom:sidebar' as userpanel %}
                                                        {% url 'chatroom:chatbox' subcategory.pk as chatbox %}
                                                        {% url 'chatroom:users' subcategory.pk as users %}
                                                        <!-- <button class="chatroom" onclick="openChatWindow('{{ userpanel }}', '{{ chatbox }}', '{{ users }}')">{{ subcategory.name }}</button> -->
                                                        <a href="{% url 'chatroom:room' subcategory.pk %}" class="chatroom">{{ subcategory.name }}</a>
                                                    {% else %}
                                                        <button class="chatroom" onclick="alert('Coming Soon.')">{{ subcategory.name }}</button>
                                                    {% endif %}
                                                </li>
                                            </ul>
                                        </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="container py-2 text-center" style="background-color: #1dbbd6">
            <p class="m-0 text-center text-dark">Copyright &copy; WannaChat 2022</p>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'home/js/scripts.js' %}"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script>
            function openChatWindow(userpanel, chatbox, users) {  
                window.open(userpanel, "My Panel", "toolbar=no,status=no,menubar=no,location=left,scrollbars=no,resizable=no,height=600,width=357,screenX=100");
                window.open(chatbox, "Chat Box", "height=600,width=657,screenX=500");
                window.open(users,"Users","height=600,width=357,screenX=1200");
            }

            $("#country").change(function () {
                var countryName = $('#country').find(":selected").val();
                $.ajax({
                    url: '/change-country/',
                    method: "GET",
                    data: {
                        'country': countryName,
                    },
                    success: function (data) {
                        console.log(data);
                        window.location.reload();
                    }
                });
            });
        </script>
    </body>
</html>

templates/message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to Wannachat</title>
</head>
<body>
    <h2>Hello {{ user.profile.name }},</h2>
    <p>Welcome to Wannachat.</p>
    <b>Please activate your account by clicking the link below.</b>
    <br>
    <a href="{{ site.domain }}{% url 'customauth:account_activation' user.email_token %}">Activate Account</a>
    <br>
    <p>Thanks</p>
</body>
</html>