chatroom/urls.py
from django.urls import path

from chatroom import views

app_name = 'chatroom'


urlpatterns = [
    path('', views.ChatDashboardView.as_view(), name='chat_dashboard'),
    path('<int:pk>/', views.ChatRoomView.as_view(), name='room'),
    path('<int:chatroom>/direct/<int:pk>/', views.DirectChatView.as_view(), name='direct_chat'),
    path('sidebar/', views.ChatRoomSidebarView.as_view(), name='sidebar'),
    path('<int:pk>/chatbox/', views.ChatBoxView.as_view(), name='chatbox'),
    path('<int:pk>/users/', views.ChatUsersView.as_view(), name='users'),
    path(
        'send-room-message/', views.SendRoomMessageView.as_view(),
        name='send_room_message'
    ),
    path(
        'send-direct-message/int:<receiver_id>/', views.SendDirectMessageView.as_view(),
        name='send_direct_message'
    ),
    path('ajax/custom/room/', views.ajax_custom_room, name='ajax_custom_room'),
    path('add-friend/<int:userid>/', views.AddFriendView.as_view(), name='add_friend'),
    path('make-friend/<int:userid>/', views.MakeFriendView.as_view(), name='make_friend'),
    path('make-family/<int:userid>/', views.MakeFamilyMemberView.as_view(), name='make_family'),
    path('make-co-worker/<int:userid>/', views.MakeCoWorkerView.as_view(), name='make_co_worker'),
]

customauth/urls.py
from django.urls import path

from customauth import views

app_name = 'customauth'


urlpatterns = [
    path('admin-login/', views.AdminLoginView.as_view(), name='admin_login'),
    path('admin-logout/', views.user_logout, name='logout'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('signup/', views.UserRegistrationView.as_view(), name='user_signup'),
    path(
        'active-account/<str:token>/', views.AccountActivationView.as_view(),
        name='account_activation'
    ),
    path('load-state/', views.load_state_view, name='load_state'),
    path('welcome/', views.WelcomePageView.as_view(), name='welcome'),
    path('confirmation/', views.ConfirmPageView.as_view(), name='confirmation'),
]

dashboard/urls.py
from django.urls import path

from dashboard import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),

    # country urls
    path(
        'country-list/', views.CountryListView.as_view(),
        name='country_list'
    ),
    path(
        'country-create/', views.CountryCreateView.as_view(),
        name='country_create'
    ),
    path(
        'country/<int:pk>/edit/', views.CountryEditView.as_view(),
        name='country_edit'
    ),
    path(
        'country/<int:pk>/status-change/',
        views.CountryStatusUpdateView.as_view(),
        name='country_status_change'
    ),
    path(
        'country/<int:pk>/delete/', views.CountryDeleteView.as_view(),
        name='country_delete'
    ),

    # category urls
    path(
        'category-list/', views.CategoryListView.as_view(),
        name='category_list'
    ),
    path(
        'category-create/', views.CategoryCreateView.as_view(),
        name='category_create'
    ),
    path(
        'category/<int:pk>/edit/', views.CategoryEditView.as_view(),
        name='category_edit'
    ),
    path(
        'category/<int:pk>/status-change/',
        views.CategoryStatusUpdateView.as_view(),
        name='category_status_change'
    ),
    path(
        'category/<int:pk>/delete/', views.CategoryDeleteView.as_view(),
        name='category_delete'
    ),

    # sub category urls
    path(
        'subcategory-list/', views.SubCategoryListView.as_view(),
        name='subcategory_list'
    ),
    path(
        'subcategory-create/', views.SubCategoryCreateView.as_view(),
        name='subcategory_create'
    ),
    path(
        'subcategory/<int:pk>/edit/', views.SubCategoryEditView.as_view(),
        name='subcategory_edit'
    ),
    path(
        'subcategory/<int:pk>/status-change/',
        views.SubCategoryStatusUpdateView.as_view(),
        name='subcategory_status_change'
    ),
    path(
        'subcategory/<int:pk>/delete/', views.SubCategoryDeleteView.as_view(),
        name='subcategory_delete'
    ),
]

django_boilerplate/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import HomeView


urlpatterns = [
    path('management/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('auth/', include('customauth.urls')),
    path('dashboard/', include('dashboard.urls')),
]

wannachat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from wannachat import views


urlpatterns = [
    path('management/', admin.site.urls),

    path('', views.HomeView.as_view(), name='home'),
    path(
        'change-country/', views.ChangeCountryView.as_view(),
        name='change_country'
    ),
    path('faq/', views.FAQPageView.as_view(), name='faq'),
    path('tos/', views.TOSPageView.as_view(), name='tos'),
    path('chat-rules/', views.ChatRulesPageView.as_view(), name='chat_rules'),
    path(
        'safety-tips/', views.SafetyTipsPageView.as_view(), name='safety_tips'
    ),
    path(
        'privacy-policy/', views.PrivacyPolicyPageView.as_view(),
        name='privacy_policy'
    ),
    path(
        'cookie-policy/', views.CookiePolicyPageView.as_view(),
        name='cookie_policy'
    ),
    path(
        'cookie-settings/', views.CookieSettingsPageView.as_view(),
        name='cookie_settings'
    ),
    path('contact/', views.ContactPageView.as_view(), name='contact'),
    path('find-friend/', views.FindFriendView.as_view(), name='find_friend'),

    path('auth/', include('customauth.urls')),
    path('chatroom/', include('chatroom.urls')),
    path('dashboard/', include('dashboard.urls')),
]

# serve media files in development environment --------------------------------
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

dashboard/views/category.py
from django.views.generic import ListView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404

from chatroom.models import Category
from chatroom.forms import CategoryForm, CategoryFilterForm


class CategoryListView(LoginRequiredMixin, ListView):
    template_name = 'dashboard/category/list.html'
    model = Category
    login_url = "/auth/admin-login/"
    paginate_by = 15
    filterset_form = CategoryFilterForm

    def get_queryset(self, **kwargs):
        objects = self.model.objects.all()
        self.filterset = self.filterset_form(
            data=self.request.GET, queryset=objects,
            request=self.request
        )
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total'] = self.filterset.qs.count()
        context['filterset_form'] = self.filterset.form
        return context


class CategoryCreateView(LoginRequiredMixin, View):
    template_name = 'dashboard/category/create.html'
    model = Category
    form_class = CategoryForm
    login_url = "/auth/admin-login/"

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        context = {
            'form': form,
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            return redirect('dashboard:category_list')
        context = {
            'form': form,
        }
        return render(request, self.template_name, context)


class CategoryEditView(LoginRequiredMixin, View):
    template_name = 'dashboard/category/edit.html'
    model = Category
    form_class = CategoryForm
    login_url = "/auth/admin-login/"

    def get(self, request, *args, **kwargs):
        category = get_object_or_404(self.model, pk=self.kwargs['pk'])
        form = self.form_class(instance=category)
        context = {
            'form': form,
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        category = get_object_or_404(self.model, pk=self.kwargs['pk'])
        form = self.form_class(request.POST, instance=category)
        if form.is_valid():
            form.save()
            return redirect('dashboard:category_list')
        context = {
            'form': form,
        }
        return render(request, self.template_name, context)


class CategoryStatusUpdateView(LoginRequiredMixin, View):
    model = Category
    login_url = "/auth/admin-login/"

    def post(self, request, *args, **kwargs):
        category = get_object_or_404(self.model, pk=self.kwargs['pk'])
        if category.is_active:
            category.is_active = False
        else:
            category.is_active = True
        category.save()
        return redirect('dashboard:category_list')


class CategoryDeleteView(LoginRequiredMixin, View):
    model = Category
    login_url = "/auth/admin-login/"

    def post(self, request, *args, **kwargs):
        category = get_object_or_404(self.model, pk=self.kwargs['pk'])
        category.delete()
        return redirect('dashboard:category_list')

dashboard/views/country.py
from django.views.generic import ListView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404

from chatroom.models import Country
from chatroom.forms import CountryForm, CountryFilterForm


class CountryListView(LoginRequiredMixin, ListView):
    template_name = 'dashboard/country/list.html'
    model = Country
    login_url = "/auth/admin-login/"
    paginate_by = 15
    filterset_form = CountryFilterForm

    def get_queryset(self, **kwargs):
        objects = self.model.objects.all()
        self.filterset = self.filterset_form(
            data=self.request.GET, queryset=objects,
            request=self.request
        )
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total'] = self.filterset.qs.count()
        context['filterset_form'] = self.filterset.form
        return context


class CountryCreateView(LoginRequiredMixin, View):
    template_name = 'dashboard/country/create.html'
    model = Country
    form_class = CountryForm
    login_url = "/auth/admin-login/"

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        context = {
            'form': form,
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            return redirect('dashboard:country_list')
        context = {
            'form': form,
        }
        return render(request, self.template_name, context)


class CountryEditView(LoginRequiredMixin, View):
    template_name = 'dashboard/country/edit.html'
    model = Country
    form_class = CountryForm
    login_url = "/auth/admin-login/"

    def get(self, request, *args, **kwargs):
        category = get_object_or_404(self.model, pk=self.kwargs['pk'])
        form = self.form_class(instance=category)
        context = {
            'form': form,
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        category = get_object_or_404(self.model, pk=self.kwargs['pk'])
        form = self.form_class(request.POST, instance=category)
        if form.is_valid():
            form.save()
            return redirect('dashboard:country_list')
        context = {
            'form': form,
        }
        return render(request, self.template_name, context)


class CountryStatusUpdateView(LoginRequiredMixin, View):
    model = Country
    login_url = "/auth/admin-login/"

    def post(self, request, *args, **kwargs):
        category = get_object_or_404(self.model, pk=self.kwargs['pk'])
        if category.is_active:
            category.is_active = False
        else:
            category.is_active = True
        category.save()
        return redirect('dashboard:country_list')


class CountryDeleteView(LoginRequiredMixin, View):
    model = Country
    login_url = "/auth/admin-login/"

    def post(self, request, *args, **kwargs):
        category = get_object_or_404(self.model, pk=self.kwargs['pk'])
        category.delete()
        return redirect('dashboard:country_list')

dashboard/views/dashboard.py
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render


class DashboardView(LoginRequiredMixin, View):
    """ Dashboard view """
    template_name = 'dashboard/dashboard.html'
    login_url = "/auth/admin-login/"

    def get(self, request):
        return render(request, self.template_name)

dashboard/views/sub_category.py
from django.views.generic import ListView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404

from chatroom.models import SubCategory
from chatroom.forms import SubCategoryForm, SubCategoryFilterForm


class SubCategoryListView(LoginRequiredMixin, ListView):
    template_name = 'dashboard/subcategory/list.html'
    model = SubCategory
    login_url = "/auth/admin-login/"
    paginate_by = 15
    filterset_form = SubCategoryFilterForm

    def get_queryset(self, **kwargs):
        objects = self.model.objects.all()
        self.filterset = self.filterset_form(
            data=self.request.GET, queryset=objects,
            request=self.request
        )
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total'] = self.filterset.qs.count()
        context['filterset_form'] = self.filterset.form
        return context


class SubCategoryCreateView(LoginRequiredMixin, View):
    template_name = 'dashboard/subcategory/create.html'
    model = SubCategory
    form_class = SubCategoryForm
    login_url = "/auth/admin-login/"

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        context = {
            'form': form,
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            return redirect('dashboard:subcategory_list')
        context = {
            'form': form,
        }
        return render(request, self.template_name, context)


class SubCategoryEditView(LoginRequiredMixin, View):
    template_name = 'dashboard/subcategory/edit.html'
    model = SubCategory
    form_class = SubCategoryForm
    login_url = "/auth/admin-login/"

    def get(self, request, *args, **kwargs):
        category = get_object_or_404(self.model, pk=self.kwargs['pk'])
        form = self.form_class(instance=category)
        context = {
            'form': form,
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        category = get_object_or_404(self.model, pk=self.kwargs['pk'])
        form = self.form_class(request.POST, instance=category)
        if form.is_valid():
            form.save()
            return redirect('dashboard:subcategory_list')
        context = {
            'form': form,
        }
        return render(request, self.template_name, context)


class SubCategoryStatusUpdateView(LoginRequiredMixin, View):
    model = SubCategory
    login_url = "/auth/admin-login/"

    def post(self, request, *args, **kwargs):
        category = get_object_or_404(self.model, pk=self.kwargs['pk'])
        if category.is_active:
            category.is_active = False
        else:
            category.is_active = True
        category.save()
        return redirect('dashboard:subcategory_list')


class SubCategoryDeleteView(LoginRequiredMixin, View):
    model = SubCategory
    login_url = "/auth/admin-login/"

    def post(self, request, *args, **kwargs):
        category = get_object_or_404(self.model, pk=self.kwargs['pk'])
        category.delete()
        return redirect('dashboard:subcategory_list')

templates/dashboard/base/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>{% block title %}{% endblock title %} | WannaChat</title>

        {% include 'dashboard/base/header.html' %}
        {% block extracss %}{% endblock extracss %}
    </head>
    <body class="hold-transition sidebar-mini layout-fixed">
        <div class="wrapper">
            <!-- Preloader -->
            <div class="preloader flex-column justify-content-center align-items-center">
                <img class="animation__shake" src="{% static 'dashboard/img/AdminLTELogo.png' %}" alt="AdminLTELogo" height="60" width="60" />
            </div>

            <!-- Navbar -->
            {% include 'dashboard/base/navbar.html' %}
            <!-- /.navbar -->

            <!-- Main Sidebar Container -->
            {% include 'dashboard/base/sidebar.html' %}

            <!-- Content Wrapper. Contains page content -->
            <div class="content-wrapper">
                <!-- Content Header (Page header) -->
                <div class="content-header">
                    <div class="container-fluid">
                        {% block breadcrumb %}
                        {% endblock breadcrumb %}
                        <!-- /.row -->
                    </div>
                    <!-- /.container-fluid -->
                </div>
                <!-- /.content-header -->

                <!-- Main content -->
                <section class="content">
                    <div class="container-fluid">
                        {% block content %}
                        {% endblock content %}
                    </div>
                    <!-- /.container-fluid -->
                </section>
                <!-- /.content -->
            </div>
            <!-- /.content-wrapper -->
            <footer class="main-footer">
                <strong>Copyright &copy; {% now 'Y' %} <a href="">WannaChat</a>.</strong>
                All rights reserved.
                <div class="float-right d-none d-sm-inline-block"><b>Version</b> 0.0.1</div>
            </footer>

            <!-- Control Sidebar -->
            <aside class="control-sidebar control-sidebar-dark">
                <!-- Control sidebar content goes here -->
            </aside>
            <!-- /.control-sidebar -->
        </div>
        <!-- ./wrapper -->

        {% include 'dashboard/base/js.html' %}
        {% block extrascript %}{% endblock extrascript %}
    </body>
</html>

templates/dashboard/base/header.html
{% load static %}

<!-- Google Font: Source Sans Pro -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback" />
<!-- Font Awesome -->
<link rel="stylesheet" href="{% static 'dashboard/plugins/fontawesome-free/css/all.min.css' %}" />
<!-- Ionicons -->
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" />
<!-- Tempusdominus Bootstrap 4 -->
<link rel="stylesheet" href="{% static 'dashboard/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}" />
<!-- iCheck -->
<link rel="stylesheet" href="{% static 'dashboard/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}" />
<!-- JQVMap -->
<link rel="stylesheet" href="{% static 'dashboard/plugins/jqvmap/jqvmap.min.css' %}" />
<!-- Theme style -->
<link rel="stylesheet" href="{% static 'dashboard/css/adminlte.min.css' %}" />
<!-- overlayScrollbars -->
<link rel="stylesheet" href="{% static 'dashboard/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}" />
<!-- Daterange picker -->
<link rel="stylesheet" href="{% static 'dashboard/plugins/daterangepicker/daterangepicker.css' %}" />
<!-- summernote -->
<link rel="stylesheet" href="{% static 'dashboard/plugins/summernote/summernote-bs4.min.css' %}" />

templates/dashboard/base/js.html
{% load static %}

<!-- jQuery -->
<script src="{% static 'dashboard/plugins/jquery/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'dashboard/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge("uibutton", $.ui.button);
</script>
<!-- Bootstrap 4 -->
<script src="{% static 'dashboard/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- ChartJS -->
<script src="{% static 'dashboard/plugins/chart.js/Chart.min.js' %}"></script>
<!-- Sparkline -->
<script src="{% static 'dashboard/plugins/sparklines/sparkline.js' %}"></script>
<!-- JQVMap -->
<script src="{% static 'dashboard/plugins/jqvmap/jquery.vmap.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/jqvmap/maps/jquery.vmap.usa.js' %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static 'dashboard/plugins/jquery-knob/jquery.knob.min.js' %}"></script>
<!-- daterangepicker -->
<script src="{% static 'dashboard/plugins/moment/moment.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/daterangepicker/daterangepicker.js' %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static 'dashboard/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<!-- Summernote -->
<script src="{% static 'dashboard/plugins/summernote/summernote-bs4.min.js' %}"></script>
<!-- overlayScrollbars -->
<script src="{% static 'dashboard/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dashboard/js/adminlte.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dashboard/js/demo.js' %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'dashboard/js/pages/dashboard.js' %}"></script>

templates/dashboard/base/sidebar.html
{% load static %}

<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{% url 'dashboard:dashboard' %}" class="brand-link">
        <img src="{% static 'dashboard/img/AdminLTELogo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: 0.8;" />
        <span class="brand-text font-weight-light">WannaChat</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{% static 'dashboard/img/user2-160x160.jpg' %}" class="img-circle elevation-2" alt="User Image" />
            </div>
            <div class="info">
                <a href="#" class="d-block">Alexander Pierce</a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class with font-awesome or any other icon font library -->
                <li class="nav-item">
                    <a href="{% url 'dashboard:dashboard' %}" class="nav-link active">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>Dashboard</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fa fa-users"></i>
                        <p>
                            Users
                            <span class="right badge badge-danger">{{ total_user }}</span>
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'dashboard:country_list' %}" class="nav-link">
                        <i class="nav-icon fa fa-list-alt"></i>
                        <p>
                            Country
                            <span class="right badge badge-danger">{{ total_country }}</span>
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'dashboard:category_list' %}" class="nav-link">
                        <i class="nav-icon fa fa-list-alt"></i>
                        <p>
                            Category
                            <span class="right badge badge-danger">{{ total_category }}</span>
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'dashboard:subcategory_list' %}" class="nav-link">
                        <i class="nav-icon fa fa-list-alt"></i>
                        <p>
                            Sub Category
                            <span class="right badge badge-danger">{{ total_subcategory }}</span>
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'customauth:logout' %}" class="nav-link">
                        <i class="nav-icon fas fa-sign-out-alt"></i>
                        <p>Logout</p>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>